### ISSUE TITLE
Release edyan/xhgui:php7.4 image

### ISSUE THREAD

**Issue by pfuhrmann** [edyan/docker-xhgui#9]
Can you please push edyan/xhgui:php7.4 image? It is documented but seems it was not pushed to docker hub?

```
docker pull edyan/xhgui:php7.4
Error response from daemon: manifest for edyan/xhgui:php7.4 not found: manifest unknown: manifest unknown
```

**Comment by edyan** [comment]
Hi, it's done, sorry I missed it when I built docker images. 
Everything is up to date. 

Thanks for your message @pfuhrmann
